### ISSUE TITLE
git-up really slow...need help to debug

### ISSUE THREAD

**Issue by bitboxer** [aanand/git-up#114]
I started to use git-up yesterday after a friend of mine showed it to me. 

Sadly it is really slow when fast-forwarding. It needs ~30 seconds per branch that needs to be forwarded.

![bildschirmfoto 2015-11-17 um 16 39 39](https://cloud.githubusercontent.com/assets/56195/11216113/d470d306-8d49-11e5-90d9-9f95424533db.png)

Can someone here help me to find out what the problem is?

Some details about my system:

```
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin15]
git version 2.6.3
hub version 2.2.2
Mac OS El Capitan 10.11.1 (15B42)
```

**Comment by benbarbour** [comment]
I'm also finding git to be painfully slow on El Capitan.

**Comment by bitboxer** [comment]
@benbarbour look into the readme, Git 2.9 does already what this thing did. It is no longer needed.
