### ISSUE TITLE
should lock git repository before and keep the lock for whole process

### ISSUE THREAD

**Issue by kretes** [aanand/git-up#36]
during git up i sometimes face 'fatal: Unable to create '<repo>/.git/index.lock': File exists.'

I understand that this is some other git process which interfere with git up.

I have Git cola (Git gui tool) and IntelliJ Idea running in the background. one of them is probably refreshing git state from time to time.

What i suggest is (if possible with git) for git up would be to acquire git repository lock before starting to updating all branches -> this would mean that either whole git up will work or it would not start if the lock was taken at the beginning. But there would be no possibility of it running and leaving working copy in unknown state in some branch or during a failed rebase...

**Comment by kinjalpadalikar** [comment]
How do we make a particular branch private or for limited usage?
