### ISSUE TITLE
Git 2.5 - Multiple worktrees support

### ISSUE THREAD

**Issue by matan129** [aanand/git-up#99]
With the new Git 2.5 release, there's officially the new feature of multiple working directories. This is available through the `git worktree <path> <branch>` command. 

This allows the user to have more than one working directory. These two directories are linked together so git prevents you from doing bad stuff like checking out the same branch on two places.

Anyway, this new functionality breaks `git up` when you're on a worktree that isn't your original one:

```
matan@matan-linux ~/Repos/2nd-worktree> git up
/var/lib/gems/1.9.1/gems/grit-2.5.0/lib/grit/git-ruby.rb:116:in `chdir': Not a directory - /home/matan/Repos/2nd-worktree/.git (Errno::ENOTDIR)
    from /var/lib/gems/1.9.1/gems/grit-2.5.0/lib/grit/git-ruby.rb:116:in `refs'
    from /var/lib/gems/1.9.1/gems/grit-2.5.0/lib/grit/ref.rb:13:in `find_all'
    from /var/lib/gems/1.9.1/gems/grit-2.5.0/lib/grit/repo.rb:213:in `heads'
    from /var/lib/gems/1.9.1/gems/git-up-0.5.12/lib/git-up.rb:158:in `remote_map'
    from /var/lib/gems/1.9.1/gems/git-up-0.5.12/lib/git-up.rb:154:in `remotes'
    from /var/lib/gems/1.9.1/gems/git-up-0.5.12/lib/git-up.rb:12:in `run'
    from /var/lib/gems/1.9.1/gems/git-up-0.5.12/bin/git-up:5:in `<top (required)>'
    from /usr/local/bin/git-up:23:in `load'
    from /usr/local/bin/git-up:23:in `<main>'

```

`git up` just doesn't detect it's in a new worktree. There's no `.git` directory in worktrees that aren't the main one.

It should use the `git rev-parse --git-common-dir` command which will yield the correct path to the `.git` directory when inside non-main worktrees.

**Comment by zx8** [comment]
:+1:
